apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: plant-catalog-service
  title: Plant Catalog Service
  description: Manage Plants, Plant Varieties and Grow Instructions
  annotations:
    github.com/project-slug: 'kravvya/GardenLog.V2023'
  tags: 
    - netcore
    - domain-service
spec:
  type: service
  owner: growers
  lifecycle: experimental
  system: plant-catalog
  domain: gardenlog.V2023
  dependsOn:
    - resource:PlantCatalog-Collection
  providesApis:
    - plant-catalog-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: plant-catalog-api
  description: Manage and retrieve plant, plant varieties and growing instructions
spec:
  type: openapi
  lifecycle: experimental
  owner: growers
  system: plant-catalog
  domain: gardenlog.V2023
  definition:
    $text: https://plantcatalogapi-containerapp.politecoast-efa2ff8d.eastus.azurecontainerapps.io/swagger/v1/swagger.json

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: PlantCatalog-Collection
  title: PlantCatalog-Collection
  description: MongoDB Coolection for PLants and Grow Instructions
spec:
  owner: growers
  system: plant-catalog
  domain: gardenlog.V2023
  type: collection
  lifecycle: experimental
  dependsOn:
    - resource:GardenLog-Db
    - resource:GardenLog2023-Cluster

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: PlantVarietyCatalog-Collection
  title: PlantVarietyCatalog-Collection
  description: MongoDB Coolection for Plant Varieties
spec:
  owner: growers
  system: plant-catalog
  domain: gardenlog.V2023
  type: collection
  lifecycle: experimental
  dependsOn:
    - resource:GardenLog-Db
    - resource:GardenLog2023-Cluster
