apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gardenlogweb
  title: GardenLog Web Client
  description: Compoenent for GardenLog Web Client
  annotations:
    github.com/project-slug: kravvya\GardenLog.V2023
  tags: 
    - blazor
spec:
  type: service
  owner: blazor-fan
  lifecycle: development
