apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gardenlogweb
  title: GardenLog Web Client
  description: Compoenent for GardenLog Web Client
  annotations:
    github.com/project-slug: kravvya\GardenLog.V2023
  tags: 
    - blazor
  links:
    - url: https://kravvya.github.io/GardenLog.V2023/
      title: Home screen
      icon: dashboard
spec:
  type: website
  owner: blazor-fan
  lifecycle: development
  system: garden-plan
  domain: gardenlog.V2023
  dependsOn:
    - component:plant-catalog-service
    - component:user-management-service
    - component:plant-harvest-service
    - component:image-catalog-service
  consumesApis:
    - plant-catalog-api
    - user-management-api
    - plant-harvest-api
    - image-catalog-api