apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: user-management-service
  title: User Management Service
  description: Component for User Management
  annotations:
    github.com/project-slug: GardenLog.V2023/gardenlog-monorepo
  tags: 
    - netcore
    - feature-service
spec:
  type: service
  owner: growers
  lifecycle: development
