apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: image-catalog-service
  title: Image Catalog Service
  description: Store and retrieve photos
  annotations:
    github.com/project-slug: 'kravvya/GardenLog.V2023/ImageCatalog'
  tags: 
    - netcore
    - feature-service
spec:
  type: service
  owner: growers
  lifecycle: experimental
  system: image-catalog
  domain: gardenlog.V2023
  dependsOn:
    - resource:ImageCatalog-Collection
    - resource:glimages
  providesApis:
    - image-catalog-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: image-catalog-api
  description: Store and retrieve photos
spec:
  type: openapi
  lifecycle: experimental
  owner: growers
  system: image-catalog
  domain: gardenlog.V2023
  definition:
    $text: https://imagecatalogapi-containerapp.politecoast-efa2ff8d.eastus.azurecontainerapps.io/swagger/v1/swagger.json

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ImageCatalog-Collection
  title: ImageCatalog-Collection
  description: MongoDB Coolection for Photos and thumbnails
spec:
  owner: growers
  system: image-catalog
  domain: gardenlog.V2023
  type: collection
  lifecycle: experimental
  dependsOn:
    - resource:GardenLog-Db
    - resource:GardenLog2023-Cluster

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: glimages
  title: GLImages Azure blob storage
  description: Azure blob store for photos and thumbnails
spec:
  owner: growers
  system: image-catalog
  domain: gardenlog.V2023
  type: azure-blob
  lifecycle: experimental