name: Build and deploy .NET application to container app plantcatalogapi-containerapp
on:
  push:
    branches: 
      - GitHub-Actions-Setup
    paths:
      - "PlantCatalog.Api"
  workflow_dispatch:
env:
  CONTAINER_APP_CONTAINER_NAME: plantcatalogapi-container
  CONTAINER_APP_NAME: plantcatalogapi-containerapp
  DOCKER_FILE_PATH: PlantCatalog.Api/Dockerfile
  PROJECT_NAME_FOR_DOCKER: plantcatalogapi
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: Checkout to the branch
      uses: actions/checkout@main

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}.azurecr.io/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
        file: ${{ env.DOCKER_FILE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # - name: Deploy to containerapp
    #   uses: azure/container-apps-deploy-action@v0
    #   with:
    #     acrName: ${{ secrets.REGISTRY_LOGIN_SERVER }}
    #     containerAppName: ${{ env.CONTAINER_APP_NAME }}
    #     resourceGroup: ${{ secrets.RESOURCE_GROUP }}
    #     acrUsername: ${{ secrets.REGISTRY_USERNAME }}
    #     acrPassword: ${{ secrets.REGISTRY_PASSWORD }}
    #     imageToDeploy: ${{ secrets.REGISTRY_LOGIN_SERVER }}.azurecr.io/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
    - name: Deploy to containerapp
      uses: azure/CLI@v1
      with:
        inlineScript: >
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --server ${{ secrets.REGISTRY_LOGIN_SERVER }}.azurecr.io --username ${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_PASSWORD }}

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --image ${{ secrets.REGISTRY_LOGIN_SERVER }}.azurecr.io/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
    - name: logout
      run: >
        az logout